/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const AgeCategory = IDL.Variant({
  'between18And35' : IDL.Null,
  'over50' : IDL.Null,
  'under18' : IDL.Null,
  'between36And50' : IDL.Null,
});
export const Participant = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'registrationTimestamp' : Time,
  'phone' : IDL.Text,
  'ageCategory' : AgeCategory,
});
export const Prize = IDL.Record({
  'placement' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'addPrize' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllParticipants' : IDL.Func([], [IDL.Vec(Participant)], ['query']),
  'getParticipantById' : IDL.Func([IDL.Nat], [Participant], ['query']),
  'getPrizesByCategory' : IDL.Func([], [IDL.Vec(Prize)], ['query']),
  'registerParticipant' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, AgeCategory],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const AgeCategory = IDL.Variant({
    'between18And35' : IDL.Null,
    'over50' : IDL.Null,
    'under18' : IDL.Null,
    'between36And50' : IDL.Null,
  });
  const Participant = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'registrationTimestamp' : Time,
    'phone' : IDL.Text,
    'ageCategory' : AgeCategory,
  });
  const Prize = IDL.Record({
    'placement' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'addPrize' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllParticipants' : IDL.Func([], [IDL.Vec(Participant)], ['query']),
    'getParticipantById' : IDL.Func([IDL.Nat], [Participant], ['query']),
    'getPrizesByCategory' : IDL.Func([], [IDL.Vec(Prize)], ['query']),
    'registerParticipant' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, AgeCategory],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };