/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AgeCategory = { 'between18And35' : null } |
  { 'over50' : null } |
  { 'under18' : null } |
  { 'between36And50' : null };
export interface Participant {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'address' : string,
  'registrationTimestamp' : Time,
  'phone' : string,
  'ageCategory' : AgeCategory,
}
export interface Prize {
  'placement' : string,
  'description' : string,
  'category' : string,
  'amount' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'getAllParticipants' : ActorMethod<[], Array<Participant>>,
  'getAllPrizes' : ActorMethod<[], Array<Prize>>,
  'getParticipantById' : ActorMethod<[bigint], Participant>,
  'getPrizesByCategory' : ActorMethod<[], Array<Prize>>,
  'registerParticipant' : ActorMethod<
    [string, string, string, string, AgeCategory],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];