/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Participant {
    id: bigint;
    name: string;
    email: string;
    address: string;
    registrationTimestamp: Time;
    phone: string;
    ageCategory: AgeCategory;
}
export interface Prize {
    placement: string;
    description: string;
    category: string;
    amount: bigint;
}
export type Time = bigint;
export enum AgeCategory {
    between18And35 = "between18And35",
    over50 = "over50",
    under18 = "under18",
    between36And50 = "between36And50"
}
export interface backendInterface {
    getAllParticipants(): Promise<Array<Participant>>;
    getAllPrizes(): Promise<Array<Prize>>;
    getParticipantById(id: bigint): Promise<Participant>;
    getPrizesByCategory(): Promise<Array<Prize>>;
    registerParticipant(name: string, address: string, email: string, phone: string, ageCategory: AgeCategory): Promise<bigint>;
}
import type { AgeCategory as _AgeCategory, Participant as _Participant, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllParticipants(): Promise<Array<Participant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllParticipants();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllParticipants();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPrizes(): Promise<Array<Prize>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPrizes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPrizes();
            return result;
        }
    }
    async getParticipantById(arg0: bigint): Promise<Participant> {
        if (this.processError) {
            try {
                const result = await this.actor.getParticipantById(arg0);
                return from_candid_Participant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getParticipantById(arg0);
            return from_candid_Participant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrizesByCategory(): Promise<Array<Prize>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrizesByCategory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrizesByCategory();
            return result;
        }
    }
    async registerParticipant(arg0: string, arg1: string, arg2: string, arg3: string, arg4: AgeCategory): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerParticipant(arg0, arg1, arg2, arg3, to_candid_AgeCategory_n6(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerParticipant(arg0, arg1, arg2, arg3, to_candid_AgeCategory_n6(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
}
function from_candid_AgeCategory_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgeCategory): AgeCategory {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Participant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Participant): Participant {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    email: string;
    address: string;
    registrationTimestamp: _Time;
    phone: string;
    ageCategory: _AgeCategory;
}): {
    id: bigint;
    name: string;
    email: string;
    address: string;
    registrationTimestamp: Time;
    phone: string;
    ageCategory: AgeCategory;
} {
    return {
        id: value.id,
        name: value.name,
        email: value.email,
        address: value.address,
        registrationTimestamp: value.registrationTimestamp,
        phone: value.phone,
        ageCategory: from_candid_AgeCategory_n4(_uploadFile, _downloadFile, value.ageCategory)
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    between18And35: null;
} | {
    over50: null;
} | {
    under18: null;
} | {
    between36And50: null;
}): AgeCategory {
    return "between18And35" in value ? AgeCategory.between18And35 : "over50" in value ? AgeCategory.over50 : "under18" in value ? AgeCategory.under18 : "between36And50" in value ? AgeCategory.between36And50 : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Participant>): Array<Participant> {
    return value.map((x)=>from_candid_Participant_n2(_uploadFile, _downloadFile, x));
}
function to_candid_AgeCategory_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgeCategory): _AgeCategory {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgeCategory): {
    between18And35: null;
} | {
    over50: null;
} | {
    under18: null;
} | {
    between36And50: null;
} {
    return value == AgeCategory.between18And35 ? {
        between18And35: null
    } : value == AgeCategory.over50 ? {
        over50: null
    } : value == AgeCategory.under18 ? {
        under18: null
    } : value == AgeCategory.between36And50 ? {
        between36And50: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
